version : 2.1

executors:
  docker-executor:
    machine:
      image: ubuntu-2204:current

orbs:
  docker: circleci/docker@2.6.0

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - docker/build:
          image: cosmospoulet/tp1-container
          tag: latest
          extra_build_args: "--pull"
      - docker/push:
          image: cosmospoulet/tp1-container
          tag: latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build